### ISSUE TITLE
mloginfo: empty lines should be skipped, currently they crash the script

### ISSUE THREAD

**Issue by rueckstiess** [rueckstiess/mtools#213]
```
 [======                                  ] 16.2 % Traceback (most recent call last):
  File "/Users/tr/virtualenvs/ve/bin/mloginfo", line 8, in <module>
    execfile(__file__)
  File "/Users/tr/Documents/code/mtools/scripts/mloginfo", line 69, in <module>
    tool.run()
  File "/Users/tr/Documents/code/mtools/scripts/mloginfo", line 64, in run
    section.run()
  File "/Users/tr/Documents/code/mtools/mtools/mloginfo/sections/distinct_section.py", line 54, in run
    for i, logevent in enumerate(self.mloginfo.logfile):
  File "/Users/tr/Documents/code/mtools/mtools/util/logfile.py", line 140, in __iter__
    le = self.next()
  File "/Users/tr/Documents/code/mtools/mtools/util/logfile.py", line 121, in next
    ret = le.set_datetime_hint(self._datetime_format, self._datetime_nextpos, self.year_rollover)
  File "/Users/tr/Documents/code/mtools/mtools/util/logevent.py", line 219, in set_datetime_hint
    if not self.split_tokens[self._datetime_nextpos-1][0].isdigit():
IndexError: list index out of range
```

**Comment by ashitaka1** [comment]
with mtools version 1.1.8 I am getting a similar error:

Traceback (most recent call last):
  File "/usr/local/bin/mlogfilter", line 9, in <module>
    load_entry_point('mtools==1.1.8', 'console_scripts', 'mlogfilter')()
  File "/usr/local/lib/python2.7/dist-packages/mtools/mlogfilter/mlogfilter.py", line 287, in main
    tool.run()
  File "/usr/local/lib/python2.7/dist-packages/mtools/mlogfilter/mlogfilter.py", line 267, in run
    for logevent in self.logfile_generator():
  File "/usr/local/lib/python2.7/dist-packages/mtools/mlogfilter/mlogfilter.py", line 181, in logfile_generator
    for logevent in self.args['logfile'][0]:
  File "/usr/local/lib/python2.7/dist-packages/mtools/util/logfile.py", line 208, in __iter__
    le = self.next()
  File "/usr/local/lib/python2.7/dist-packages/mtools/util/logfile.py", line 190, in next
    ret = le.set_datetime_hint(self._datetime_format, self._datetime_nextpos, self.year_rollover)
  File "/usr/local/lib/python2.7/dist-packages/mtools/util/logevent.py", line 246, in set_datetime_hint
    if not self.split_tokens[self._datetime_nextpos-1][0].isdigit():
IndexError: list index out of range

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://markenshops24.com/attack.php?h>

 

klaus@hebsgaard.dk
