### ISSUE TITLE
mloginfo: Handle downgrade of major version style of logs (ie. ISODate in 2.6 -> mills in 2.4)

### ISSUE THREAD

**Issue by gianpaj** [rueckstiess/mtools#240]
```
2014-06-18T14:24:41.487+0100 [initandlisten] MongoDB starting : pid=97415 port=27017 dbpath=/data/db 64-bit host=Gianfranco-10gen.local
2014-06-18T14:24:41.487+0100 [initandlisten] 
2014-06-18T14:24:41.487+0100 [initandlisten] ** WARNING: soft rlimits too low. Number of files is 256, should be at least 1000
2014-06-18T14:24:41.487+0100 [initandlisten] db version v2.6.2
2014-06-18T14:24:41.487+0100 [initandlisten] git version: 4d06e27876697d67348a397955b46dabb8443827
2014-06-18T14:24:41.487+0100 [initandlisten] build info: Darwin mci-osx108-3.build.10gen.cc 12.3.0 Darwin Kernel Version 12.3.0: Sun Jan  6 22:37:10 PST 2013; root:xnu-2050.22.13~1/RELEASE_X86_64 x86_64 BOOST_LIB_VERSION=1_49
2014-06-18T14:24:41.487+0100 [initandlisten] allocator: system
2014-06-18T14:24:41.487+0100 [initandlisten] options: { systemLog: { destination: "file", logAppend: true, path: "Desktop/mongod.log" } }
2014-06-18T14:24:41.487+0100 [initandlisten] journal dir=/data/db/journal
2014-06-18T14:24:41.487+0100 [initandlisten] recover : no journal files present, no recovery needed
2014-06-18T14:24:41.515+0100 [initandlisten] waiting for connections on port 27017
2014-06-18T14:24:45.367+0100 [signalProcessingThread] got signal 2 (Interrupt: 2), will terminate after current cmd ends
2014-06-18T14:24:45.367+0100 [signalProcessingThread] now exiting
2014-06-18T14:24:45.367+0100 [signalProcessingThread] dbexit: 
2014-06-18T14:24:45.367+0100 [signalProcessingThread] shutdown: going to close listening sockets...
2014-06-18T14:24:45.367+0100 [signalProcessingThread] closing listening socket: 12
2014-06-18T14:24:45.368+0100 [signalProcessingThread] closing listening socket: 13
2014-06-18T14:24:45.368+0100 [signalProcessingThread] removing socket file: /tmp/mongodb-27017.sock
2014-06-18T14:24:45.368+0100 [signalProcessingThread] shutdown: going to flush diaglog...
2014-06-18T14:24:45.368+0100 [signalProcessingThread] shutdown: going to close sockets...
2014-06-18T14:24:45.368+0100 [signalProcessingThread] shutdown: waiting for fs preallocator...
2014-06-18T14:24:45.368+0100 [signalProcessingThread] shutdown: lock for final commit...
2014-06-18T14:24:45.368+0100 [signalProcessingThread] shutdown: final commit...
2014-06-18T14:24:45.378+0100 [signalProcessingThread] shutdown: closing all files...
2014-06-18T14:24:45.379+0100 [signalProcessingThread] closeAllFiles() finished
2014-06-18T14:24:45.379+0100 [signalProcessingThread] journalCleanup...
2014-06-18T14:24:45.379+0100 [signalProcessingThread] removeJournalFiles
2014-06-18T14:24:45.380+0100 [signalProcessingThread] shutdown: removing fs lock...
2014-06-18T14:24:45.380+0100 [signalProcessingThread] dbexit: really exiting now


***** SERVER RESTARTED *****


Wed Jun 18 14:24:54.248 [initandlisten] MongoDB starting : pid=97432 port=27017 dbpath=/data/db/ 64-bit host=Gianfranco-10gen.local
Wed Jun 18 14:24:54.248 [initandlisten] 
Wed Jun 18 14:24:54.248 [initandlisten] ** WARNING: soft rlimits too low. Number of files is 256, should be at least 1000
Wed Jun 18 14:24:54.248 [initandlisten] db version v2.4.10
Wed Jun 18 14:24:54.248 [initandlisten] git version: e3d78955d181e475345ebd60053a4738a4c5268a
Wed Jun 18 14:24:54.248 [initandlisten] build info: Darwin bs-osx-106-x86-64-2.10gen.cc 10.8.0 Darwin Kernel Version 10.8.0: Tue Jun  7 16:32:41 PDT 2011; root:xnu-1504.15.3~1/RELEASE_X86_64 x86_64 BOOST_LIB_VERSION=1_49
Wed Jun 18 14:24:54.248 [initandlisten] allocator: system
Wed Jun 18 14:24:54.248 [initandlisten] options: { logappend: true, logpath: "Desktop/mongod.log" }
Wed Jun 18 14:24:54.249 [initandlisten] journal dir=/data/db/journal
Wed Jun 18 14:24:54.249 [initandlisten] recover : no journal files present, no recovery needed
Wed Jun 18 14:24:54.272 [initandlisten] build index admin.system.users { user: 1, userSource: 1 }
Wed Jun 18 14:24:54.274 [initandlisten] build index done.  scanned 4 total records. 0.001 secs
Wed Jun 18 14:24:54.287 [websvr] admin web console waiting for connections on port 28017
Wed Jun 18 14:24:54.287 [initandlisten] waiting for connections on port 27017
Wed Jun 18 14:24:56.903 [signalProcessingThread] got signal 2 (Interrupt: 2), will terminate after current cmd ends
Wed Jun 18 14:24:56.903 [signalProcessingThread] now exiting
Wed Jun 18 14:24:56.903 dbexit: 
Wed Jun 18 14:24:56.903 [signalProcessingThread] shutdown: going to close listening sockets...
Wed Jun 18 14:24:56.903 [signalProcessingThread] closing listening socket: 10
Wed Jun 18 14:24:56.903 [signalProcessingThread] closing listening socket: 11
Wed Jun 18 14:24:56.904 [signalProcessingThread] closing listening socket: 12
Wed Jun 18 14:24:56.904 [signalProcessingThread] removing socket file: /tmp/mongodb-27017.sock
Wed Jun 18 14:24:56.904 [signalProcessingThread] shutdown: going to flush diaglog...
Wed Jun 18 14:24:56.904 [signalProcessingThread] shutdown: going to close sockets...
Wed Jun 18 14:24:56.904 [signalProcessingThread] shutdown: waiting for fs preallocator...
Wed Jun 18 14:24:56.904 [signalProcessingThread] shutdown: lock for final commit...
Wed Jun 18 14:24:56.904 [signalProcessingThread] shutdown: final commit...
Wed Jun 18 14:24:56.908 [signalProcessingThread] shutdown: closing all files...
Wed Jun 18 14:24:56.908 [signalProcessingThread] closeAllFiles() finished
Wed Jun 18 14:24:56.908 [signalProcessingThread] journalCleanup...
Wed Jun 18 14:24:56.908 [signalProcessingThread] removeJournalFiles
Wed Jun 18 14:24:56.908 [signalProcessingThread] shutdown: removing fs lock...
Wed Jun 18 14:24:56.908 dbexit: really exiting now
```

```
$ mloginfo --connections Desktop/mongod.log
     source: Desktop/mongod.log
      start: 2014 Jun 18 14:24:41
        end: 2014 Jun 18 14:24:56
date format: iso8601-local
     length: 67
     binary: mongod
    version: 2.6.2 -> 2.4.10

CONNECTIONS
Traceback (most recent call last):
  File "/usr/local/bin/mloginfo", line 10, in <module>
    execfile(__file__)
  File "/Users/gianfranco/github/rueckstiess/mtools/scripts/mloginfo", line 69, in <module>
    tool.run()
  File "/Users/gianfranco/github/rueckstiess/mtools/scripts/mloginfo", line 64, in run
    section.run()
  File "/Users/gianfranco/github/rueckstiess/mtools/mtools/mloginfo/sections/connection_section.py", line 39, in run
    for logevent in self.mloginfo.logfile:
  File "/Users/gianfranco/github/rueckstiess/mtools/mtools/util/logfile.py", line 140, in __iter__
    le = self.next()
  File "/Users/gianfranco/github/rueckstiess/mtools/mtools/util/logfile.py", line 121, in next
    ret = le.set_datetime_hint(self._datetime_format, self._datetime_nextpos, self.year_rollover)
  File "/Users/gianfranco/github/rueckstiess/mtools/mtools/util/logevent.py", line 220, in set_datetime_hint
    if not self.split_tokens[self._datetime_nextpos-1][0].isdigit():
IndexError: list index out of range
```

Going from 2.4 to 2.6 works fine.

I believe the problem are the empty lines in between `SERVER RESTARTED` after 2.6-style logs are detected

**Comment by stennie** [comment]
Fixed by #252
