### ISSUE TITLE
mloginfo: IndexError: list index out of range & cannot do a non-empty take from an empty axes.

### ISSUE THREAD

**Issue by zazchor** [rueckstiess/mtools#281]
I parse a 1.5G log file on `Ubuntu 14.04`

```
$ mloginfo mongod.log-20140912 --queries
     source: mongod.log-20140912
      start: 2014 Sep 11 06:37:06
        end: 2014 Sep 12 06:54:07
date format: iso8601-local
     length: 2666325
     binary: mongod
    version: 2.6.1

QUERIES
 [===============================         ] 77.1 % Traceback (most recent call last):
  File "/usr/local/bin/mloginfo", line 69, in <module>
    tool.run()
  File "/usr/local/bin/mloginfo", line 64, in run
    section.run()
  File "/usr/local/lib/python2.7/dist-packages/mtools/mloginfo/sections/query_section.py", line 43, in run
    for i, le in enumerate(logfile):
  File "/usr/local/lib/python2.7/dist-packages/mtools/util/logfile.py", line 140, in __iter__
    le = self.next()
  File "/usr/local/lib/python2.7/dist-packages/mtools/util/logfile.py", line 121, in next
    ret = le.set_datetime_hint(self._datetime_format, self._datetime_nextpos, self.year_rollover)
  File "/usr/local/lib/python2.7/dist-packages/mtools/util/logevent.py", line 219, in set_datetime_hint
    if not self.split_tokens[self._datetime_nextpos-1][0].isdigit():
IndexError: list index out of range
```

Then I get first 10'000 lines from original log and parse

```
$ mloginfo mongod_2.log --queries
     source: mongod_2.log
      start: 2014 Sep 05 06:46:55
        end: 2014 Sep 05 09:30:07
date format: iso8601-local
     length: 100000
     binary: unknown
    version: >= 2.6 (iso8601 format)

QUERIES

Traceback (most recent call last):
  File "/usr/local/bin/mloginfo", line 69, in <module>
    tool.run()
  File "/usr/local/bin/mloginfo", line 64, in run
    section.run()
  File "/usr/local/lib/python2.7/dist-packages/mtools/mloginfo/sections/query_section.py", line 74, in run
    stats['95%'] = np.percentile(group_events, 95)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 3042, in percentile
    interpolation=interpolation)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 2791, in _ureduce
    r = func(a, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 3131, in _percentile
    x1 = take(ap, indices_below, axis=axis) * weights_below
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 121, in take
    return take(indices, axis, out, mode)
IndexError: cannot do a non-empty take from an empty axes.
```

**Comment by gianpaj** [comment]
@zazchor can you upload 10/15 lines in a logfile which has these empty lines?

For your information, while your file a 2.6 mongod log, we found that 3.0 sometimes asserts with new lines and maybe an issue for mtools in general. (#357 - LogFile: handle newlines lines)

**Comment by zazchor** [comment]
Hi sorry, I did not use mloginfo for a while
This is what's I got in `mtools version 1.1.5`

With a 5MB log file without blank lines (checked with `grep "^$" mongod.log`) I still got 

```
     source: mongod.log
      start: 2015 May 03 06:49:32
        end: 2015 May 03 13:24:34
date format: iso8601-local
     length: 16929
     binary: unknown
    version: >= 2.6 (iso8601 format)

QUERIES

Traceback (most recent call last):
  File "/usr/local/bin/mloginfo", line 69, in <module>
    tool.run()
  File "/usr/local/bin/mloginfo", line 64, in run
    section.run()
  File "/usr/local/lib/python2.7/dist-packages/mtools/mloginfo/sections/query_section.py", line 90, in run
    print_table(table_rows, titles, uppercase_headers=False)
  File "/usr/local/lib/python2.7/dist-packages/mtools/util/print_table.py", line 4, in print_table
    keys = rows[0].keys()
IndexError: list index out of range
```

After upgrade to `mtools version 1.1.8` then it works fine now with same log file.
Looks like the error is fixed.

**Comment by gianpaj** [comment]
cool. thanks for letting us know
