### ISSUE TITLE
mlogfilter loops forever for some datetimes

### ISSUE THREAD

**Issue by gianpaj** [rueckstiess/mtools#301]
See this log file:

```
Fri Oct 10 17:22:11.839 [signalProcessingThread] shutdown: lock for final commit...
Fri Oct 10 17:22:11.839 [signalProcessingThread] shutdown: final commit...
Fri Oct 10 17:22:11.841 [signalProcessingThread] shutdown: closing all files...
Fri Oct 10 17:22:11.841 [signalProcessingThread] closeAllFiles() finished
Fri Oct 10 17:22:11.841 [signalProcessingThread] journalCleanup...
Fri Oct 10 17:22:11.841 [signalProcessingThread] removeJournalFiles
Fri Oct 10 17:22:11.841 [signalProcessingThread] shutdown: removing fs lock...
Fri Oct 10 17:22:11.841 dbexit: really exiting now


***** SERVER RESTARTED *****


Fri Oct 10 17:22:48.175 [initandlisten] MongoDB starting : pid=93249 port=27017 dbpath=/data/db/ 64-bit host=Gianfranco-10gen.local
Fri Oct 10 17:22:48.175 [initandlisten]
Fri Oct 10 17:22:48.175 [initandlisten] ** WARNING: soft rlimits too low. Number of files is 256, should be at least 1000
Fri Oct 10 17:22:48.175 [initandlisten] db version v2.4.11
Fri Oct 10 17:22:48.175 [initandlisten] git version: fa13d1ee8da0f112f588570b4070f73d7af2f7fd
Fri Oct 10 17:22:48.175 [initandlisten] build info: Darwin bs-osx-106-x86-64-2.10gen.cc 10.8.0 Darwin Kernel Version 10.8.0: Tue Jun  7 16:32:41 PDT 2011; root:xnu-1504.15.3~1/RELEASE_X86_64 x86_64 BOOST_LIB_VERSION=1_49
Fri Oct 10 17:22:48.175 [initandlisten] allocator: system
Fri Oct 10 17:22:48.175 [initandlisten] options: { logappend: true, logpath: "Desktop/test-mlogfilter-issue-50.log" }
Fri Oct 10 17:22:48.176 [initandlisten] journal dir=/data/db/journal
Fri Oct 10 17:22:48.176 [initandlisten] recover : no journal files present, no recovery needed
Fri Oct 10 17:22:48.298 [websvr] admin web console waiting for connections on port 28017
Fri Oct 10 17:22:48.299 [initandlisten] waiting for connections on port 27017
Fri Oct 10 17:48:52.642 [signalProcessingThread] got signal 2 (Interrupt: 2), will terminate after current cmd ends
Fri Oct 10 17:48:52.644 [signalProcessingThread] now exiting
```

These work fine:

```
mlogfilter test-mlogfilter-issue-50.log --from Fri Oct 10 17:22:11.841

mlogfilter test-mlogfilter-issue-50.log --from Fri Oct 10 17:22:48.176
```

These loop for ever

```
mlogfilter test-mlogfilter-issue-50.log --from Fri Oct 10 17:22:48.175

mlogfilter test-mlogfilter-issue-50.log --from Fri Oct 10 17:22:48

mlogfilter test-mlogfilter-issue-50.log --from Fri Oct 10 17:22:11.842
```

If you stop the process this is the stack trace:

```
Traceback (most recent call last):
  File "/usr/local/bin/mlogfilter", line 10, in <module>
    execfile(__file__)
  File "/Users/gianfranco/github/rueckstiess/mtools/scripts/mlogfilter", line 287, in <module>
    tool.run()
  File "/Users/gianfranco/github/rueckstiess/mtools/scripts/mlogfilter", line 267, in run
    for logevent in self.logfile_generator():
  File "/Users/gianfranco/github/rueckstiess/mtools/scripts/mlogfilter", line 173, in logfile_generator
    logfile.fast_forward( max(start_limits) )
  File "/Users/gianfranco/github/rueckstiess/mtools/mtools/util/logfile.py", line 396, in fast_forward
    le = self._find_curr_line(prev=True)
  File "/Users/gianfranco/github/rueckstiess/mtools/mtools/util/logfile.py", line 343, in _find_curr_line
    logevent = self.next()
  File "/Users/gianfranco/github/rueckstiess/mtools/mtools/util/logfile.py", line 151, in next
    elif le.datetime:
  File "/Users/gianfranco/github/rueckstiess/mtools/mtools/util/logevent.py", line 176, in datetime
    dt = self._match_datetime_pattern(split_tokens[offs:offs+4])
  File "/Users/gianfranco/github/rueckstiess/mtools/mtools/util/logevent.py", line 270, in _match_datetime_pattern
    dt = dateutil.parser.parse(' '.join(tokens[:4]), default=datetime(year, 1, 1))
  File "/Library/Python/2.7/site-packages/dateutil/parser.py", line 748, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/Library/Python/2.7/site-packages/dateutil/parser.py", line 310, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/Library/Python/2.7/site-packages/dateutil/parser.py", line 489, in _parse
    res.second, res.microsecond = _parsems(l[i+1])
  File "/Library/Python/2.7/site-packages/dateutil/parser.py", line 934, in _parsems
    return int(i), int(f.ljust(6, "0")[:6])
KeyboardInterrupt
```

I tried debugging `logfile.py` but didn't manage to understand where the bug could be.

This loops even says `roll forward until we found a line with a datetime`:
https://github.com/rueckstiess/mtools/blob/develop/mtools/util/logfile.py#L342

So not sure why it gets stuck

**Comment by stennie** [comment]
This bug is caused by the newlines around the restart in the example log file:
```

***** SERVER RESTARTED *****

```

The current logic in  [`_find_current_line(prev=True)`](https://github.com/rueckstiess/mtools/blob/284bcf4640d23c209acf01d29fa2e749192f0ca2/mtools/util/logfile.py#L398) assumes that it is possible to start from the newline prior to the current position and read forward to find a valid log line. If that isn't the case, the log position will not change and mtools will get stuck in an infinite loop.

Workarounds could be to either use a different `--from` date (one preceded by a valid log line) or to remove or filter the problematic logs with an `awk`/`sed`/... command-line recipe before piping through `mlogfilter`.

Current versions of MongoDB (3.0+) include datestamps for restarts so this is no longer a common issue, but the bug is still present for logs that have unexpected newlines.
