### ISSUE TITLE
mplotqueries gives exception when drawing, but saving image works

### ISSUE THREAD

**Issue by ali-bugdayci** [rueckstiess/mtools#305]
Hi,

Working with the m202 lesson homework 6.3.

mplotqueries gives the following exception:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
    return self.func(*args)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 276, in resize
    self.show()
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 349, in draw
    tkagg.blit(self._tkphoto, self.renderer._renderer, colormode=2)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/tkagg.py", line 20, in blit
    tk.call("PyAggImagePhoto", photoimage, id(aggimage), colormode, id(bbox_array))
TclError
```

Mplotqueries does not draw, but when I save it as an image, it saves and opens without any problem. I have installed mtools and matplotlib:

```
~% mplotqueries --version
mtools version 1.1.6

~% dpkg --list | grep matplot
ii  python-matplotlib                               1.3.1-1ubuntu5                             amd64        Python based plotting system in a style similar to Matlab
ii  python-matplotlib-data                          1.3.1-1ubuntu5                             all          Python based plotting system (data package)
```

**Comment by stennie** [comment]
Closing old bug report. All the software versions have moved on :)
