### ISSUE TITLE
mloginfo throws error with old numpy-1.4.1

### ISSUE THREAD

**Issue by drmirror** [rueckstiess/mtools#332]
A customer got the error below when running mloginfo --queries with numpy-1.4.1 installed. The error went away when we upgraded to numpy-1.9.1. I think this should be in the documentation or in the dependencies.

Traceback (most recent call last):
  File "/usr/bin/mloginfo", line 83, in <module>
    tool.run()
  File "/usr/bin/mloginfo", line 78, in run
    section.run()
  File "/usr/lib/python2.6/site-packages/mtools/mloginfo/sections/query_section.py", line 92, in run
    stats['95%'] = np.percentile(group_events, 95) if group_events else '-'
AttributeError: 'module' object has no attribute 'percentile'

**Comment by rueckstiess** [comment]
Agreed, this should be in the INSTALL.md file. For the record, a NumPy version of at least 1.8.0 or higher is required.
