### ISSUE TITLE
mlaunch --auth not working with v3.0?

### ISSUE THREAD

**Issue by kangas** [rueckstiess/mtools#333]
```
$ mlaunch --version
mtools version 1.1.7

$ ./workspace/mongo/mongod --version
db version v3.0.0-rc9-pre-
git version: dfccaaff651d1ba04d82c7c73f0e3157ea7be6a8

$ mlaunch init --single --port=8000 --binarypath=workspace/mongo --auth --username hello --password world
launching: workspace/mongo/mongod on port 8000
```

data/mongod.log shows:

```
2015-02-11T16:38:55.969-0500 I NETWORK  [initandlisten] waiting for connections on port 8000
2015-02-11T16:38:56.015-0500 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:60996 #1 (1 connection now open)
2015-02-11T16:38:56.015-0500 I ACCESS   [conn1] note: no users configured in admin.system.users, allowing localhost access
2015-02-11T16:38:56.016-0500 I NETWORK  [conn1] end connection 127.0.0.1:60996 (0 connections now open)
2015-02-11T16:38:56.017-0500 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:60997 #2 (1 connection now open)
2015-02-11T16:38:56.019-0500 I NETWORK  [conn2] end connection 127.0.0.1:60997 (0 connections now open)
2015-02-11T16:38:56.019-0500 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:60998 #3 (1 connection now open)
2015-02-11T16:38:56.021-0500 I ACCESS   [conn3] Unauthorized not authorized on admin to execute command { usersInfo: "hello" }
```

Try to connect:

```
$ ./mongo --version
MongoDB shell version: 3.0.0-rc9-pre-

$ ./mongo --port 8000 --username hello --password world
MongoDB shell version: 3.0.0-rc9-pre-
connecting to: 127.0.0.1:8000/test
2015-02-11T16:41:10.803-0500 E QUERY    Error: 18 Authentication failed.
    at DB._authOrThrow (src/mongo/shell/db.js:1236:32)
    at (auth):6:8
    at (auth):7:2 at src/mongo/shell/db.js:1236
exception: login failed
```

Log now shows

```
2015-02-11T16:41:10.776-0500 I ACCESS   [conn6] SCRAM-SHA-1 authentication failed for hello on test ; UserNotFound Could not find user hello@test
```

Am I doing something wrong?

**Comment by kangas** [comment]
Likewise, with same instance:

```
$ mlaunch stop --single --port=8000 --binarypath=workspace/mongo --auth --username hello --password world
no nodes stopped.

$ ps aux | grep mongod
kangas          12639   0.4  0.7  2751564  56104   ??  S     4:38PM   0:02.37 workspace/mongo/mongod --dbpath /Users/kangas/data/db --logpath /Users/kangas/data/mongod.log --port 8000 --logappend --fork --keyFile /Users/kangas/data/keyfile
```

**Comment by rueckstiess** [comment]
Hi @kangas, mlaunch creates the user on the _admin_ database by default. If you connect via `mongo` like this, it should work: 

```
./mongo --port 8000 --username hello --password world --authenticationDatabase admin
```

If you want to create the user on the _test_ database instead, add `--auth-db test` to your mlaunch call like this:

```
mlaunch init --single --port=8000 --binarypath=workspace/mongo --auth --username hello --password world --auth-db test
```

Side note: you do not need to repeat all the parameters when you stop an instance. A simple `mlaunch stop` suffices.

Let me know if that doesn't solve the problem.

**Comment by kangas** [comment]
I suspected operator error was the most likely explanation. But strangely, it still doesn't seem to work:

```
$ mlaunch init --single --port=8000 --binarypath=workspace/mongo --auth --username hello --password world
launching: workspace/mongo/mongod on port 8000

$ ./mongo --port 8000 --username hello --password world --authenticationDatabase admin
MongoDB shell version: 3.0.0-rc9-pre-
connecting to: 127.0.0.1:8000/test
2015-02-11T23:20:28.027-0500 E QUERY    Error: 18 Authentication failed.
    at DB._authOrThrow (src/mongo/shell/db.js:1236:32)
    at (auth):6:8
    at (auth):7:2 at src/mongo/shell/db.js:1236
exception: login failed
```

Log shows
```
2015-02-11T23:20:27.993-0500 I ACCESS   [conn5] SCRAM-SHA-1 authentication failed for hello on admin ; UserNotFound Could not find user hello@admin
```

"mlaunch stop" shows:
```
$ mlaunch stop
Traceback (most recent call last):
...
pymongo.errors.OperationFailure: command SON([('shutdown', 1), ('force', True)]) failed: not authorized on admin to execute command { shutdown: 1, force: true }
```

**Comment by rueckstiess** [comment]
Interesting, I just tried with rc8 and it worked without errors. let me try on master...

**Comment by rueckstiess** [comment]
master works for me as well, exact same commands as yours. All I did was change your `workload/mongo` binarypath to my own binarypath.

```
(ve)tr@enter:~/Documents/tmp$ mlaunch init --single --port=8000 --binarypath=~/Documents/code/mongo --auth --username hello --password world
launching: ~/Documents/code/mongo/mongod on port 8000
(ve)tr@enter:~/Documents/tmp$ ~/Documents/code/mongo/mongo --port 8000 --username hello --password world --authenticationDatabase admin
MongoDB shell version: 3.1.0-pre-
connecting to: 127.0.0.1:8000/test
Server has startup warnings:
2015-02-12T16:27:07.672+1100 I CONTROL  [initandlisten]
2015-02-12T16:27:07.672+1100 I CONTROL  [initandlisten] ** NOTE: This is a development version (3.1.0-pre-) of MongoDB.
2015-02-12T16:27:07.672+1100 I CONTROL  [initandlisten] **       Not recommended for production.
2015-02-12T16:27:07.673+1100 I CONTROL  [initandlisten]
>
bye
```

Can you add `--verbose` to the init command, or alternatively run `mlaunch list --startup`? Both of these show you exactly how the process was launched. Then try to manually run it exactly the same way?

**Comment by kangas** [comment]
I've repro'd on my Linux box on r3.0.0-rc8, latest master, and latest v3.0. Now I'm really baffled.

How can I see the details of how the user is added? --verbose only shows the startup details.

Maybe I have an outdated pymongo? Something else installed? I am running "scons core" to build the server. On both systems (linux and OS X) I have installed mtools via "sudo pip install -U mtools".

Sample output with r3.0.0-rc8 on Ubuntu 12.04 LTS.

```
kangas@beefsupreme:~/workspace/mongo ((r3.0.0-rc8))
$ mlaunch init --verbose --single --port=8000 --binarypath=. --auth --username hello --password world
creating directory: /data02/workspace/mongo/data/db
waiting for nodes to shutdown...
launching: ./mongod  --dbpath /data02/workspace/mongo/data/db --logpath /data02/workspace/mongo/data/mongod.log --port 8000 --logappend --fork --keyFile /data02/workspace/mongo/data/keyfile
waiting for nodes to start...
added user hello on admin database
writing .mlaunch_startup file.
done.

kangas@beefsupreme:~/workspace/mongo ((r3.0.0-rc8))
$ mlaunch list --startup

PROCESS    PORT    STATUS     PID    STARTUP COMMAND

single     8000    running    -      ./mongod  --dbpath /data02/workspace/mongo/data/db --logpath /data02/workspace/mongo/data/mongod.log --port 8000 --logappend --fork --keyFile /data02/workspace/mongo/data/keyfile

kangas@beefsupreme:~/workspace/mongo ((r3.0.0-rc8))
$ ./mongo --port 8000 --username hello --password world --authenticationDatabase admin
MongoDB shell version: 3.1.0-pre-
connecting to: 127.0.0.1:8000/test
2015-02-12T12:01:01.915-0500 E QUERY    Error: 18 Authentication failed.
    at DB._authOrThrow (src/mongo/shell/db.js:1236:32)
    at (auth):6:8
    at (auth):7:2 at src/mongo/shell/db.js:1236
exception: login failed

kangas@beefsupreme:~/workspace/mongo ((r3.0.0-rc8))
$ mlaunch stop
Traceback (most recent call last):
  File "/usr/local/bin/mlaunch", line 1300, in <module>
    tool.run()
  File "/usr/local/bin/mlaunch", line 238, in run
    getattr(self, self.args['command'])()
  File "/usr/local/bin/mlaunch", line 425, in stop
    shutdown_host(port, username, password, authdb)
  File "/usr/local/bin/mlaunch", line 92, in shutdown_host
    mc.admin.command('shutdown', force=True)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 396, in command
    msg, allowable_errors)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 147, in _check_command_response
    raise OperationFailure(msg % errmsg, code)
pymongo.errors.OperationFailure: command SON([('shutdown', 1), ('force', True)]) failed: not authorized on admin to execute command { shutdown: 1, force: true }

kangas@beefsupreme:~/workspace/mongo ((r3.0.0-rc8))
$ cat data/.mlaunch_startup
{"protocol_version": 2, "parsed_args": {"username": "hello", "auth_db": "admin", "name": "replset", "replicaset": false, "auth_roles": ["dbAdminAnyDatabase", "readWriteAnyDatabase", "userAdminAnyDatabase", "clusterAdmin"], "hostname": "beefsupreme", "auth": true, "port": 8000, "sharded": null, "single": true, "arbiter": false, "mongos": 1, "binarypath": ".", "command": "init", "no_progressbar": false, "password": "world", "config": 1, "nodes": 3, "dir": "/data02/workspace/mongo/data", "verbose": true}, "startup_info": {"8000": "./mongod  --dbpath /data02/workspace/mongo/data/db --logpath /data02/workspace/mongo/data/mongod.log --port 8000 --logappend --fork --keyFile /data02/workspace/mongo/data/keyfile "}, "unknown_args": [], "mtools_version": "1.1.7"}
```

**Comment by kangas** [comment]
I just manually did the following on a mongod that I started manually (using the mlaunch-generated keyfile and same command line). Then shell login works fine.

```
$ ./mongo --port 8000
MongoDB shell version: 3.1.0-pre-
connecting to: 127.0.0.1:8000/test
> use admin
switched to db admin
> db.createUser({user:"hello", pwd:"world", roles:["dbAdminAnyDatabase", "readWriteAnyDatabase", "userAdminAnyDatabase", "clusterAdmin"]})
Successfully added user: {
        "user" : "hello",
        "roles" : [
                "dbAdminAnyDatabase",
                "readWriteAnyDatabase",
                "userAdminAnyDatabase",
                "clusterAdmin"
        ]
}
>
bye
kangas@beefsupreme:~/workspace/mongo (master)
$ ./mongo --port 8000 --username hello --password world --authenticationDatabase admin
MongoDB shell version: 3.1.0-pre-
connecting to: 127.0.0.1:8000/test
Server has startup warnings:
2015-02-12T12:18:30.118-0500 I CONTROL  [initandlisten]
2015-02-12T12:18:30.118-0500 I CONTROL  [initandlisten] ** WARNING: You are running on a NUMA machine.
2015-02-12T12:18:30.118-0500 I CONTROL  [initandlisten] **          We suggest launching mongod like this to avoid performance problems:
2015-02-12T12:18:30.118-0500 I CONTROL  [initandlisten] **              numactl --interleave=all mongod [other options]
2015-02-12T12:18:30.118-0500 I CONTROL  [initandlisten]
>
bye
```

But curiously, mlaunch stop still fails as before.

I think I've isolated the problem to pymongo. I had pymongo 2.6.2. I upgraded to pymongo 2.8 and all seems well now.

So maybe we need to bubble up some info that the users are not added correctly? I'm curious where that information was lost.

**Comment by rueckstiess** [comment]
Okay thanks, it's possible I don't handle the error when creating a user. I'll look into it. It should at least throw an error if the user can't be generated. 

I'll try to repro with pymongo 2.6.2 when I get a chance.

Is `mlaunch stop` also working for you now?

**Comment by kangas** [comment]
Yes, "mlaunch stop" works correctly now

**Comment by akira-kurogane** [comment]
pymongo version 2.6.* was a problem for the following test case as well.

```
mlaunch --sharded 2 --config 3 --single --mongos 3 --auth --username adminuser --password adminpass --oplogSize 10
mongo localhost:27017/admin --username adminuser --password adminpass --eval 'db.createUser({user: "billyboy", pwd: "fuzzbutt", roles: [ "readWriteAnyDatabase" ]})'
"2015-02-24T14:20:36.999+1100 Error: couldn't add user: User and role management commands require auth data to have schema version 3 but found 1 at src/mongo/shell/db.js:1004"
```

I don't know what the underlying difference was but after a "pip install --upgrade pymongo" to v2.8 the schema version error disappeared.
