### ISSUE TITLE
mloginfo reading from system.profile seems broken

### ISSUE THREAD

**Issue by rueckstiess** [rueckstiess/mtools#353]
```
mloginfo --queries localhost/test.system.profile
     source: test.system.profile
Traceback (most recent call last):
  File "/Users/tr/virtualenvs/ve/bin/mloginfo", line 9, in <module>
    load_entry_point('mtools==1.1.8', 'console_scripts', 'mloginfo')()
  File "/Users/tr/Documents/code/mtools/mtools/mloginfo/mloginfo.py", line 82, in main
    tool.run()
  File "/Users/tr/Documents/code/mtools/mtools/mloginfo/mloginfo.py", line 45, in run
    print "       host: %s" % (self.logfile.hostname + ':' + self.logfile.port if self.logfile.hostname else "unknown")
AttributeError: 'ProfileCollection' object has no attribute 'hostname'
```

**Comment by rueckstiess** [comment]
Yes, there was an inconsistency between logfiles and system.profile inputs... that should be fixed now.
