### ISSUE TITLE
mtools supporting mongo 3.0

### ISSUE THREAD

**Issue by dbachrac** [rueckstiess/mtools#373]
Do i need to be at python 2.8.x for the current version of mtools 1.1.8 to work with mongo 3.0.4?

File "/usr/lib/python2.6/site-packages/mtools/mloginfo/mloginfo.py", line 82, in main
tool.run()

**Comment by dbachrac** [comment]
Adding a bit more context 

mloginfo lcomqndbv04_mongod_071015.log --queries
     source: lcomqndbv04_mongod_071015.log
       host: unknown
      start: 2015 Jul 10 04:10:07.296
        end: 2015 Jul 10 11:55:45.501
date format: iso8601-local
     length: 53219
     binary: unknown
    version: >= 3.0 (iso8601 format, level, component)
    storage: unknown

QUERIES
 [                                        ] 0.0 % Traceback (most recent call last):
  File "/usr/bin/mloginfo", line 9, in <module>
    load_entry_point('mtools==1.1.8', 'console_scripts', 'mloginfo')()
  File "/usr/lib/python2.6/site-packages/mtools/mloginfo/mloginfo.py", line 82, in main
    tool.run()
  File "/usr/lib/python2.6/site-packages/mtools/mloginfo/mloginfo.py", line 77, in run
    section.run()
  File "/usr/lib/python2.6/site-packages/mtools/mloginfo/sections/query_section.py", line 51, in run
    for i, le in enumerate(logfile):
  File "/usr/lib/python2.6/site-packages/mtools/util/logfile.py", line 208, in __iter__
    le = self.next()
  File "/usr/lib/python2.6/site-packages/mtools/util/logfile.py", line 190, in next
    ret = le.set_datetime_hint(self._datetime_format, self._datetime_nextpos, self.year_rollover)
  File "/usr/lib/python2.6/site-packages/mtools/util/logevent.py", line 246, in set_datetime_hint
    if not self.split_tokens[self._datetime_nextpos-1][0].isdigit():
IndexError: list index out of range

**Comment by gianpaj** [comment]
This is not a pymongo or mongodb specific version issue. Is the fact that some log lines do not begin with the date. (see #372)

Closing as duplicate
