### ISSUE TITLE
init replicaset fails when secondaries are inaccessible

### ISSUE THREAD

**Issue by dotmanila** [rueckstiess/mtools#383]
In my test below, acme.domain.com resolves to a different server, however in real case if the primary cannot access the secondaries when initiating replicaset this error is received.

This can be fixed locally of course with /etc/hosts, however, since we are running locally, shouldn't we override the host to localhost?

This for example is connecting to localhost:

https://github.com/rueckstiess/mtools/blob/master/mtools/mlaunch/mlaunch.py#L1095

But here it resolves the hostname:

https://github.com/rueckstiess/mtools/blob/master/mtools/mlaunch/mlaunch.py#L1254

```
[revin@acme mngo_3_0_6]$ mlaunch init --dir=/home/revin/msb/mngo_3_0_6/ --replicaset --nodes 2 --binarypath /home/revin/mongodb/3.0.6/bin
launching: /home/revin/mongodb/3.0.6/bin/mongod on port 27017
launching: /home/revin/mongodb/3.0.6/bin/mongod on port 27018
command {'replSetInitiate': {'_id': 'replset', 'members': [{'host': 'acme.domain.com:27017', '_id': 0, 'votes': 1}, {'host': 'acme.domain.com:27018', '_id': 1, 'votes': 1}]}} on namespace admin.$cmd failed: No host described in new configuration 1 for replica set replset maps to this node  - will retry
command {'replSetInitiate': {'_id': 'replset', 'members': [{'host': 'acme.domain.com:27017', '_id': 0, 'votes': 1}, {'host': 'acme.domain.com:27018', '_id': 1, 'votes': 1}]}} on namespace admin.$cmd failed: No host described in new configuration 1 for replica set replset maps to this node  - will retry
command {'replSetInitiate': {'_id': 'replset', 'members': [{'host': 'acme.domain.com:27017', '_id': 0, 'votes': 1}, {'host': 'acme.domain.com:27018', '_id': 1, 'votes': 1}]}} on namespace admin.$cmd failed: No host described in new configuration 1 for replica set replset maps to this node  - will retry
command {'replSetInitiate': {'_id': 'replset', 'members': [{'host': 'acme.domain.com:27017', '_id': 0, 'votes': 1}, {'host': 'acme.domain.com:27018', '_id': 1, 'votes': 1}]}} on namespace admin.$cmd failed: No host described in new configuration 1 for replica set replset maps to this node  - will retry
^CTraceback (most recent call last):
  File "/usr/bin/mlaunch", line 9, in <module>
    load_entry_point('mtools==1.1.9', 'console_scripts', 'mlaunch')()
  File "/usr/lib/python2.7/site-packages/mtools/mlaunch/mlaunch.py", line 1337, in main
    tool.run()
  File "/usr/lib/python2.7/site-packages/mtools/mlaunch/mlaunch.py", line 254, in run
    getattr(self, self.args['command'])()
  File "/usr/lib/python2.7/site-packages/mtools/mlaunch/mlaunch.py", line 364, in init
    self._initiate_replset(nodes[0], self.args['name'])
  File "/usr/lib/python2.7/site-packages/mtools/mlaunch/mlaunch.py", line 1106, in _initiate_replset
    time.sleep(1)
KeyboardInterrupt
```

**Comment by stennie** [comment]
Fixed by #510
