### ISSUE TITLE
--storageEngine mmapv1 --csrs crashes mlaunch

### ISSUE THREAD

**Issue by kevinadi** [rueckstiess/mtools#441]
CSRS requires the config servers to be running WiredTiger, but passing `--storageEngine mmapv1` to mlaunch will also pass that parameter into the config servers.

The command line I used is:

```
mlaunch init --sharded 2 --replicaset --storageEngine mmapv1 --verbose --csrs
```

**Comment by Steve-Hand** [comment]
This appears to be a problem with MongoDB version > 3.2. Using v3.2.10 works just fine

The error I'm seeing with MongoDB version > 3.2:
```
mlaunch init --dir /data/mtoolstest --port 28000 --sharded 2 --replicaset --storageEngine mmapv1 --verbose -csrs 
Detected mongod version: 3.3.10
creating directory: /data/mtoolstest/shard01/rs1/db
creating directory: /data/mtoolstest/shard01/rs2/db
creating directory: /data/mtoolstest/shard01/rs3/db
creating directory: /data/mtoolstest/shard02/rs1/db
creating directory: /data/mtoolstest/shard02/rs2/db
creating directory: /data/mtoolstest/shard02/rs3/db
creating directory: /data/mtoolstest/configRepl/rs1/db
waiting for nodes to shutdown...
creating cluster without auth for setup, will enable auth at the end...
launching: mongod --replSet shard01 --dbpath /data/mtoolstest/shard01/rs1/db --logpath /data/mtoolstest/shard01/rs1/mongod.log --port 28001 --logappend --fork  --storageEngine mmapv1 --shardsvr
launching: mongod --replSet shard01 --dbpath /data/mtoolstest/shard01/rs2/db --logpath /data/mtoolstest/shard01/rs2/mongod.log --port 28002 --logappend --fork  --storageEngine mmapv1 --shardsvr
launching: mongod --replSet shard01 --dbpath /data/mtoolstest/shard01/rs3/db --logpath /data/mtoolstest/shard01/rs3/mongod.log --port 28003 --logappend --fork  --storageEngine mmapv1 --shardsvr
launching: mongod --replSet shard02 --dbpath /data/mtoolstest/shard02/rs1/db --logpath /data/mtoolstest/shard02/rs1/mongod.log --port 28004 --logappend --fork  --storageEngine mmapv1 --shardsvr
launching: mongod --replSet shard02 --dbpath /data/mtoolstest/shard02/rs2/db --logpath /data/mtoolstest/shard02/rs2/mongod.log --port 28005 --logappend --fork  --storageEngine mmapv1 --shardsvr
launching: mongod --replSet shard02 --dbpath /data/mtoolstest/shard02/rs3/db --logpath /data/mtoolstest/shard02/rs3/mongod.log --port 28006 --logappend --fork  --storageEngine mmapv1 --shardsvr
launching: mongod --replSet configRepl --dbpath /data/mtoolstest/configRepl/rs1/db --logpath /data/mtoolstest/configRepl/rs1/mongod.log --port 28007 --logappend --fork  --storageEngine mmapv1 --configsvr
waiting for nodes to start...
Initiating config server replica set.
Traceback (most recent call last):
  File "/usr/local/bin/mlaunch", line 9, in <module>
    load_entry_point('mtools', 'console_scripts', 'mlaunch')()
  File "/Users/shand/Documents/Development/mtools_steve/mtools/mlaunch/mlaunch.py", line 1426, in main
    tool.run()
  File "/Users/shand/Documents/Development/mtools_steve/mtools/mlaunch/mlaunch.py", line 259, in run
    getattr(self, self.args['command'])()
  File "/Users/shand/Documents/Development/mtools_steve/mtools/mlaunch/mlaunch.py", line 326, in init
    self._initiate_replset(members[0], "configRepl")
  File "/Users/shand/Documents/Development/mtools_steve/mtools/mlaunch/mlaunch.py", line 1165, in _initiate_replset
    con['admin'].command({'replSetInitiate':self.config_docs[name]})
  File "/usr/local/lib/python2.7/site-packages/pymongo/database.py", line 481, in command
    codec_options, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pymongo/database.py", line 393, in _command
    allowable_errors)
  File "/usr/local/lib/python2.7/site-packages/pymongo/pool.py", line 244, in command
    self._raise_connection_failure(error)
  File "/usr/local/lib/python2.7/site-packages/pymongo/pool.py", line 372, in _raise_connection_failure
    raise error
pymongo.errors.AutoReconnect: connection closed
```

**Comment by Steve-Hand** [comment]
It appears that the support for "csrs" is entirely broken. Use "--csrs" with v3.2.0 and neither are the config server RSs running nor are any of the shard RSs running.

**Comment by Steve-Hand** [comment]
Sorry, the issue is cause by the "storageEngine" parameter. CSRS members must use WT. mtools does not currently support having mixed storage engines.
