### ISSUE TITLE
mtools 1.2.2: `pip install mtools --upgrade` does not upgrade PyMongo

### ISSUE THREAD

**Issue by stennie** [rueckstiess/mtools#450]
The 1.2.2 pip package for mtools apparently doesn't enforce the same requirements as [requirements.txt](https://github.com/rueckstiess/mtools/blob/develop/requirements.txt), so may have unexpected errors if an incompatible version of a dependency is installed.

To repro:
- mtools 1.2.1 and pymongo 2.7.2 installed
- `pip install mtools --upgrade`
- run `mlaunch --replicaset --arbiter --port 30000 --nodes 2`

Commands like `mlaunch list` and `mlaunch stop` will fail with a traceback similar to:

```
mlaunch list
Traceback (most recent call last):
  File "/usr/local/bin/mlaunch", line 9, in <module>
    load_entry_point('mtools==1.2.2', 'console_scripts', 'mlaunch')()
  File "/Library/Python/2.7/site-packages/mtools/mlaunch/mlaunch.py", line 1410, in main
    tool.run()
  File "/Library/Python/2.7/site-packages/mtools/mlaunch/mlaunch.py", line 259, in run
    getattr(self, self.args['command'])()
  File "/Library/Python/2.7/site-packages/mtools/mlaunch/mlaunch.py", line 555, in list
    self.discover()
  File "/Library/Python/2.7/site-packages/mtools/mlaunch/mlaunch.py", line 803, in discover
    self.cluster_tags['primary'].append( mrsc.primary[1] )
  File "/Library/Python/2.7/site-packages/pymongo/database.py", line 211, in __getitem__
    return self.__getattr__(name)
  File "/Library/Python/2.7/site-packages/pymongo/database.py", line 201, in __getattr__
    return Collection(self, name)
  File "/Library/Python/2.7/site-packages/pymongo/collection.py", line 101, in __init__
    "of %s" % (basestring.__name__,))
```

Manually installing latest PyMongo should fix:
  `pip install pymongo --upgrade`

Check version of PyMongo:
  `python -c "import pymongo; print(pymongo.version);"`

**Comment by stennie** [comment]
With mtools 1.2.4 it will be possible to try to install some or all extra dependencies via `pip`: https://github.com/rueckstiess/mtools/blob/develop/INSTALL.md#additional-dependencies.
