### ISSUE TITLE
Error while creating replica set with name and auth args

### ISSUE THREAD

**Issue by KozlovAV** [rueckstiess/mtools#476]
```
mlaunch init --replicaset --nodes 3 --name RS1 --hostname localhost --auth
```
will result in 
```
replica set 'RS1' initialized.
waiting for primary to add a user.
Traceback (most recent call last):
  File "/usr/local/bin/mlaunch", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/mtools/mlaunch/mlaunch.py", line 1443, in main
    tool.run()
  File "/usr/local/lib/python2.7/site-packages/mtools/mlaunch/mlaunch.py", line 260, in run
    getattr(self, self.args['command'])()
  File "/usr/local/lib/python2.7/site-packages/mtools/mlaunch/mlaunch.py", line 414, in init
    if self._wait_for_primary():
  File "/usr/local/lib/python2.7/site-packages/mtools/mlaunch/mlaunch.py", line 1228, in _wait_for_primary
    hosts = [x['host'] for x in self.config_docs['replset']['members']]
KeyError: 'replset'
```

The problem in hardcoded replica set name ('replset') in line 1228 
```
hosts = [x['host'] for x in self.config_docs['replset']['members']]
rs_name = self.config_docs['replset']['_id']
```

Maybe self.args['name'] should be OK

**Comment by stennie** [comment]
@KozlovAV Thanks for the bug report! Can you confirm which version of mtools you are using?

**Comment by KozlovAV** [comment]
mlaunch --version
mtools version 1.2.3

**Comment by Bastian82** [comment]
I can reproduce this issue aswell:
mtools version 1.3.1
