### ISSUE TITLE
mlaunch will not work with default values(Python 2.7.13 W7 x64 Mongo 3.4)

### ISSUE THREAD

**Issue by crazy54** [rueckstiess/mtools#479]
I cannot get mlaunch to work, even with default values and nothing defined. I have Windows 7 x64 and running Mongo 3.4  and Python 2.7.13.  Here is the error 

**C:\Users\jeremy.hall>**`mlaunch --single --sharded 3
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\mlaunch.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\mtools\mlaunch\mlaunch.py", line 1438, in main
    tool.run()
  File "c:\python27\lib\site-packages\mtools\mlaunch\mlaunch.py", line 260, in run
    getattr(self, self.args['command'])()
  File "c:\python27\lib\site-packages\mtools\mlaunch\mlaunch.py", line 280, in init
    current_version = self.getMongoDVersion()
  File "c:\python27\lib\site-packages\mtools\mlaunch\mlaunch.py", line 475, in getMongoDVersion
    if current_version.rindex('v') > 0:`

**Comment by rueckstiess** [comment]
Unfortunately `mlaunch` is not supported on Windows platforms. This is documented in the Windows installation instructions, but it's a bit hidden. We should make that information more visible in the README. 

https://github.com/rueckstiess/mtools/wiki/mtools-Installation-on-Windows-Server-2008-R2,-32bit#usage
