### ISSUE TITLE
[mlogfilter] Can't filter log by time

### ISSUE THREAD

**Issue by keithmork** [rueckstiess/mtools#525]
```
mlogfilter /Users/keithmo/Downloads/mongo-27017.log --from "end -1min"

Traceback (most recent call last):
  File "/usr/local/bin/mlogfilter", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/mtools/mlogfilter/mlogfilter.py", line 287, in main
    tool.run()
  File "/usr/local/lib/python2.7/site-packages/mtools/mlogfilter/mlogfilter.py", line 267, in run
    for logevent in self.logfile_generator():
  File "/usr/local/lib/python2.7/site-packages/mtools/mlogfilter/mlogfilter.py", line 173, in logfile_generator
    logfile.fast_forward( max(start_limits) )
  File "/usr/local/lib/python2.7/site-packages/mtools/util/logfile.py", line 509, in fast_forward
    if le.datetime >= start_dt:
TypeError: can't compare datetime.datetime to NoneType
```

The variables in logfile.py and logevent.py:

```
dt: None
dt: None
dt: None
dt: None
dt: None
dt: None
dt: None
dt: None
dt: None
dt: None
dt: 2017-09-25 03:25:24.076000+08:00
dt: 2017-09-25 17:12:29.852000+08:00
dt: None
dt: None
dt: None
dt: None
dt: None
dt: None
dt: None
dt: None
dt: None
dt: None
dt: None
dt: None
dt: None
dt: None
dt: None
dt: None
dt: None
dt: None
dt: None
dt: None
le: 2017-09-25T03:25:24.058+0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:52351 #3773489 (192 connections now open)
le.datetime: None
start_dt: 2017-09-25 17:11:29.852000+08:00
```

The log file looks like this: (with 770k+ lines, > 3GB)

```
2017-09-25T17:12:29.438+0800 I QUERY    [conn3773345] query health.b_hospital query: { name: { $in: [ "康哲无锡医院", "康哲无锡医院" ] } } planSummary: COLLSCAN ntoreturn:0 ntoskip:0 nscanned:0 nscannedObjects:71258 keyUpdates:0 writeConflicts:0 numYields:556 nreturned:1 reslen:327 locks:{ Global: { acquireCount: { r: 557 } }, MMAPV1Journal: { acquireCount: { r: 557 } }, Database: { acquireCount: { r: 557 } }, Collection: { acquireCount: { R: 557 } } } 40ms
2017-09-25T17:12:29.484+0800 I QUERY    [conn3773345] query health.b_hospital query: { name: { $in: [ "康哲无锡医院", "康哲无锡医院" ] } } planSummary: COLLSCAN ntoreturn:0 ntoskip:0 nscanned:0 nscannedObjects:71258 keyUpdates:0 writeConflicts:0 numYields:556 nreturned:1 reslen:327 locks:{ Global: { acquireCount: { r: 557 } }, MMAPV1Journal: { acquireCount: { r: 557 } }, Database: { acquireCount: { r: 557 } }, Collection: { acquireCount: { R: 557 } } } 38ms
2017-09-25T17:12:29.528+0800 I QUERY    [conn3773345] query health.b_hospital query: { name: { $in: [ "康哲陕西医院" ] } } planSummary: COLLSCAN ntoreturn:0 ntoskip:0 nscanned:0 nscannedObjects:71258 keyUpdates:0 writeConflicts:0 numYields:556 nreturned:1 reslen:380 locks:{ Global: { acquireCount: { r: 557 } }, MMAPV1Journal: { acquireCount: { r: 557 } }, Database: { acquireCount: { r: 557 } }, Collection: { acquireCount: { R: 557 } } } 38ms
2017-09-25T17:12:29.572+0800 I QUERY    [conn3773345] query health.b_hospital query: { name: { $in: [ "康哲无锡医院", "康哲无锡医院" ] } } planSummary: COLLSCAN ntoreturn:0 ntoskip:0 nscanned:0 nscannedObjects:71258 keyUpdates:0 writeConflicts:0 numYields:556 nreturned:1 reslen:327 locks:{ Global: { acquireCount: { r: 557 } }, MMAPV1Journal: { acquireCount: { r: 557 } }, Database: { acquireCount: { r: 557 } }, Collection: { acquireCount: { R: 557 } } } 38ms
2017-09-25T17:12:29.617+0800 I QUERY    [conn3773345] query health.b_hospital query: { name: { $in: [ "康哲陕西医院", "康哲陕西医院" ] } } planSummary: COLLSCAN ntoreturn:0 ntoskip:0 nscanned:0 nscannedObjects:71258 keyUpdates:0 writeConflicts:0 numYields:556 nreturned:1 reslen:380 locks:{ Global: { acquireCount: { r: 557 } }, MMAPV1Journal: { acquireCount: { r: 557 } }, Database: { acquireCount: { r: 557 } }, Collection: { acquireCount: { R: 557 } } } 38ms
2017-09-25T17:12:29.664+0800 I QUERY    [conn3773345] query health.b_hospital query: { name: { $in: [ "康哲湖北医院", "康哲湖北医院" ] } } planSummary: COLLSCAN ntoreturn:0 ntoskip:0 nscanned:0 nscannedObjects:71258 keyUpdates:0 writeConflicts:0 numYields:556 nreturned:1 reslen:348 locks:{ Global: { acquireCount: { r: 557 } }, MMAPV1Journal: { acquireCount: { r: 557 } }, Database: { acquireCount: { r: 557 } }, Collection: { acquireCount: { R: 557 } } } 39ms
2017-09-25T17:12:29.713+0800 I QUERY    [conn3773345] query health.b_hospital query: { name: { $in: [ "康哲无锡医院", "康哲总部医院" ] } } planSummary: COLLSCAN ntoreturn:0 ntoskip:0 nscanned:0 nscannedObjects:71258 keyUpdates:0 writeConflicts:0 numYields:556 nreturned:2 reslen:587 locks:{ Global: { acquireCount: { r: 557 } }, MMAPV1Journal: { acquireCount: { r: 557 } }, Database: { acquireCount: { r: 557 } }, Collection: { acquireCount: { R: 557 } } } 42ms
2017-09-25T17:12:29.759+0800 I QUERY    [conn3773345] query health.b_hospital query: { name: { $in: [ "康哲湖北医院", "康哲湖北医院" ] } } planSummary: COLLSCAN ntoreturn:0 ntoskip:0 nscanned:0 nscannedObjects:71258 keyUpdates:0 writeConflicts:0 numYields:556 nreturned:1 reslen:348 locks:{ Global: { acquireCount: { r: 557 } }, MMAPV1Journal: { acquireCount: { r: 557 } }, Database: { acquireCount: { r: 557 } }, Collection: { acquireCount: { R: 557 } } } 40ms
2017-09-25T17:12:29.803+0800 I QUERY    [conn3773345] query health.b_hospital query: { name: { $in: [ "康哲河南医院", "康哲河南医院" ] } } planSummary: COLLSCAN ntoreturn:0 ntoskip:0 nscanned:0 nscannedObjects:71258 keyUpdates:0 writeConflicts:0 numYields:556 nreturned:1 reslen:361 locks:{ Global: { acquireCount: { r: 557 } }, MMAPV1Journal: { acquireCount: { r: 557 } }, Database: { acquireCount: { r: 557 } }, Collection: { acquireCount: { R: 557 } } } 37ms
2017-09-25T17:12:29.852+0800 I QUERY    [conn3773345] query health.b_hospital query: { name: { $in: [ "康哲无锡医院", "康哲无锡医院" ] } } planSummary: COLLSCAN ntoreturn:0 ntoskip:0 nscanned:0 nscannedObjects:71258 keyUpdates:0 writeConflicts:0 numYields:556 nreturned:1 reslen:327 locks:{ Global: { acquireCount: { r: 557 } }, MMAPV1Journal: { acquireCount: { r: 557 } }, Database: { acquireCount: { r: 557 } }, Collection: { acquireCount: { R: 557 } } } 42ms
```

env: 
- macbook pro 2016, macOS Sierra 10.12.6
- python 2.7.14
- zsh
- mongodb 3.0.3

**Comment by stennie** [comment]
@keithmork Thanks for the bug report. Can you confirm the version of `mlogfilter` you are using ( `mlogfilter --version`) as well as the version of MongoDB server the logs are from?

Also, in your sample debug output you have some lines with empty dates. Are those represented in your sample log file (i.e. the date is not being parsed correctly) or are there other lines in the log file missing dates?

Regards,
Stennie

**Comment by keithmork** [comment]
@stennie Thanks for your response. mtools version is 1.3.0, mongo version is v3.0.3.

And those 2 non-empty datetime are the start time and end time of the log file.

```
     source: /XXX/mongo-27017.log
       host: unknown
      start: 2017 Sep 25 03:25:24.076
        end: 2017 Sep 25 17:12:29.852
date format: iso8601-local
     length: 744381
     binary: unknown
    version: >= 3.0 (iso8601 format, level, component)
    storage: unknown
```

I split the log file(3.28GB) every 100k lines, and mlogfilter works well with ALL the smaller files(< 100MB), so the format of the lines may not be the root cause.

**Comment by stennie** [comment]
@keithmork Any suggestions on how to reproduce this issue?

Thanks,
Stennie

**Comment by stennie** [comment]
Not sure how to reproduce this issue and haven't had any related bug reports, so closing.
