### ISSUE TITLE
mlaunch: psutil dependency missing

### ISSUE THREAD

**Issue by davemichels** [rueckstiess/mtools#557]
The psutil dependency for mlaunch is no longer present. It looks like it was missed on commit https://github.com/rueckstiess/mtools/commit/739610a87a246d001e48479daf60e1c4eaac352a. This was the refactor of setup.py to use extras_require.

Suggested fix is to add psutil (not sure what version you want) to setup.py line 21. Workaround is to install psutil manually.
 
### Expected behavior
All mlaunch dependencies including psutil should install with `pip install mtools[mlaunch]`.

### Actual/current behavior
psutil does not install with `pip install mtools[mlaunch]`.

### Steps to reproduce the actual/current behavior
```
dave.michels@m-dmichels:~/repos/external/mtools$ mktmpenv
New python executable in /Users/dave.michels/.python/virtualenvs/tmp-a3c30077dca1c3d/bin/python2.7
Also creating executable in /Users/dave.michels/.python/virtualenvs/tmp-a3c30077dca1c3d/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /Users/dave.michels/.python/virtualenvs/tmp-a3c30077dca1c3d/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/dave.michels/.python/virtualenvs/tmp-a3c30077dca1c3d/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/dave.michels/.python/virtualenvs/tmp-a3c30077dca1c3d/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/dave.michels/.python/virtualenvs/tmp-a3c30077dca1c3d/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/dave.michels/.python/virtualenvs/tmp-a3c30077dca1c3d/bin/get_env_details
This is a temporary environment. It will be deleted when you run 'deactivate'.
(tmp-a3c30077dca1c3d) dave.michels@m-dmichels:~/.python/virtualenvs/tmp-a3c30077dca1c3d$ pip install mtools[mlaunch]
Collecting mtools[mlaunch]
  Using cached mtools-1.3.2-py2-none-any.whl
Collecting pymongo>=3.3; extra == "mlaunch" (from mtools[mlaunch])
  Using cached pymongo-3.5.1-cp27-none-macosx_10_12_x86_64.whl
Installing collected packages: pymongo, mtools
Successfully installed mtools-1.3.2 pymongo-3.5.1
(tmp-a3c30077dca1c3d) dave.michels@m-dmichels:~/.python/virtualenvs/tmp-a3c30077dca1c3d$ mlaunch
Traceback (most recent call last):
  File "/Users/dave.michels/.python/virtualenvs/tmp-a3c30077dca1c3d/bin/mlaunch", line 7, in <module>
    from mtools.mlaunch.mlaunch import main
  File "/Users/dave.michels/.python/virtualenvs/tmp-a3c30077dca1c3d/lib/python2.7/site-packages/mtools/mlaunch/mlaunch.py", line 6, in <module>
    import psutil
ImportError: No module named psutil
```

### Environment
| Software         | Version
| ---------------- | -------
| mtools           | 1.3.2
| MongoDB server   | 3.4.10
| Operating system | MacOS 10.12.6
| Python         | 2.7.14

**Comment by stennie** [comment]
@davemichels Thanks for the bug report .. indeed an oversight!

Regards,
Stennie

**Comment by davemichels** [comment]
You're welcome but I think I added the bug report too soon. mlaunch is also missing python-dateutil.

**Comment by kevinadi** [comment]
@davemichels I believe python-dateutil is installed correctly. Here's what I discovered:

Before:
```
$ pip list
pip (8.1.1)
setuptools (20.7.0)
six (1.11.0)
wheel (0.29.0)
```

Install:
```
$ pip install --no-cache-dir -e'.[mlaunch]'
Obtaining file:///home/ubuntu/mtools
...[cut]...
Successfully installed mtools psutil-5.4.1 pymongo-3.5.1 python-dateutil-2.2 six-1.11.0
```

After:
```
$ pip list
mtools (1.3.3.dev0, /home/ubuntu/mtools)
pip (8.1.1)
psutil (5.4.1)
pymongo (3.5.1)
python-dateutil (2.2)
setuptools (20.7.0)
six (1.11.0)
wheel (0.29.0)
```

Test run:
```
$ mlaunch
usage: mlaunch [-h] [--version] [--no-progressbar]
               {init,start,stop,restart,list,kill} ...
mlaunch: error: too few arguments
```

Note that this was done using the latest `develop` branch, which included the fix for the lack of `psutil` requirement.

Could you confirm if the above steps have different result in your case? Thanks.
