### ISSUE TITLE
mlogfilter --scan TypeError in Python 3.6.5

### ISSUE THREAD

**Issue by stennie** [rueckstiess/mtools#618]
### Expected behavior

`mlogfilter --scan` should match log lines with inefficient index usage.

### Steps to reproduce the actual/current behavior
```
$ mlogfilter --scan mongod.log
Traceback (most recent call last):
  File "~/.pyenv/versions/3.6.5/bin/mlogfilter", line 11, in <module>
    load_entry_point('mtools', 'console_scripts', 'mlogfilter')()
  File "~/mtools/mtools/mlogfilter/mlogfilter.py", line 355, in main
    tool.run()
  File "~/mtools/mtools/mlogfilter/mlogfilter.py", line 341, in run
    if all([f.accept(logevent) for f in self.filters]):
  File "~/mtools/mtools/mlogfilter/mlogfilter.py", line 341, in <listcomp>
    if all([f.accept(logevent) for f in self.filters]):
  File "~/mtools/mtools/mlogfilter/filters/tablescan_filter.py", line 35, in accept
    ns = logevent.nscanned
  File "~/mtools/mtools/util/logevent.py", line 472, in nscanned
    self._extract_counters()
  File "~/mtools/mtools/util/logevent.py", line 605, in _extract_counters
    if self.operation:
  File "~/mtools/mtools/util/logevent.py", line 375, in operation
    self._extract_operation_and_namespace()
  File "~/mtools/mtools/util/logevent.py", line 400, in _extract_operation_and_namespace
    _ = self.thread
  File "~/mtools/mtools/util/logevent.py", line 338, in thread
    len(split_tokens) <= self.datetime_nextpos):
TypeError: '<=' not supported between instances of 'int' and 'NoneType'
```

### Environment
| Software         | Version
| ---------------- | -------
| mtools           | 1.4.1
| python | 3.6.5

**Comment by stennie** [comment]
Fixed via #634
