### ISSUE TITLE
mloginfo --queries TypeError - python 3.6.5

### ISSUE THREAD

**Issue by andreynikk** [rueckstiess/mtools#636]
trying to run the following command on mongo logs:
  mloginfo mongod.log --queries > log.txt
 

### Actual/current behavior

getting the following error:

> ➜  mongo mloginfo mongod.log --queries > log.txt
 [=========================               ] 62.4 % Traceback (most recent call last):
  File "/Users/anikitin/anaconda/bin/mloginfo", line 11, in <module>
    sys.exit(main())
  File "/Users/anikitin/anaconda/lib/python3.6/site-packages/mtools/mloginfo/mloginfo.py", line 95, in main
    tool.run()
  File "/Users/anikitin/anaconda/lib/python3.6/site-packages/mtools/mloginfo/mloginfo.py", line 90, in run
    section.run()
  File "/Users/anikitin/anaconda/lib/python3.6/site-packages/mtools/mloginfo/sections/query_section.py", line 81, in run
    pattern=le.pattern, duration=le.duration)
  File "/Users/anikitin/anaconda/lib/python3.6/site-packages/mtools/util/logevent.py", line 431, in pattern
    self._pattern = self._find_pattern('query: ')
  File "/Users/anikitin/anaconda/lib/python3.6/site-packages/mtools/util/logevent.py", line 716, in _find_pattern
    return json2pattern(search_str)
  File "/Users/anikitin/anaconda/lib/python3.6/site-packages/mtools/util/pattern.py", line 82, in json2pattern
    doc = json.loads(s, object_hook=_decode_pattern_dict)
  File "/Users/anikitin/anaconda/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/Users/anikitin/anaconda/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/anikitin/anaconda/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/Users/anikitin/anaconda/lib/python3.6/site-packages/mtools/util/pattern.py", line 38, in _decode_pattern_dict
    value = _decode_pattern_list(value)
  File "/Users/anikitin/anaconda/lib/python3.6/site-packages/mtools/util/pattern.py", line 20, in _decode_pattern_list
    rv = sorted(rv)
TypeError: '<' not supported between instances of 'dict' and 'dict'

### Environment

| Software         | Version
| ---------------- | -------
| mtools           |  1.4.1
| python           |  3.6.5
| MongoDB server   |  3.2.1
| Operating system |  macOSX

**Comment by kevinadi** [comment]
Thanks for the report.

A similar issue was reported in #618 and was fixed in the latest `develop` branch commit (https://github.com/rueckstiess/mtools/commit/6ff062d6f8ce542969bfa4d5f85b0694a5970d3b). If you don't mind, is it possible for you to try using the latest `develop` branch and see if the problem still occur? There are instructions on [Using a development branch](http://blog.rueckstiess.com/mtools/development.html).

Also, could you please attach a link to the problematic log file? I'd like to understand what type of log line triggers this issue.

**Comment by andreynikk** [comment]
@kevinadi thanks for fixing this, unfortunately I'm unable to share log file.
