### ISSUE TITLE
mplotqueries always fails with Attribute Error: 'Scatter PlotType' object has no attribute 'regex'

### ISSUE THREAD

**Issue by dlombard** [rueckstiess/mtools#656]
Everytime I try mplotqueries, it fails after parsing with an attribute error
 
`
Loaded overlay: 613ae3dc
()
SCATTER plot
   id   #points  group
    1      6834  admin.$cmd
    2       253  local.oplog.rs
    3        84  stg-psautogroup.ServiceMenu
    4        40  stg-psautogroup.ServiceVehicle
    5        34  local.$cmd
    6        20  admin.system.users
    7        10  local.system.replset
    8         8  None
    9         5  local.clustermanager
   10         4  stg-psautogroup.User
   11         4  stg-psautogroup.CustomerMaster
   12         3  stg-psautogroup.Appointment
   13         1  stage-cacargroup
   14         1  stg-psautogroup
   15         1  stg-innovationmotors
   16         1  stg-cacargroup-prod-dump
   17         1  test
   18         1  stg-cacargroup-archived
   19         1  local
   20         1  stg-gillautogroup
   21         1  stg-amcautogroup
   22         1  tekionglobal
   23         1  stg-cacargroup
   24         1  admin
()
SCATTER plot
   id   #points  group
    1       757  query
Traceback (most recent call last):
  File "/Users/dlombard/py_env/bin/mplotqueries", line 11, in <module>
    sys.exit(main())
  File "/Users/dlombard/py_env/lib/python2.7/site-packages/mtools/mplotqueries/mplotqueries.py", line 678, in main
    tool.run()
  File "/Users/dlombard/py_env/lib/python2.7/site-packages/mtools/mplotqueries/mplotqueries.py", line 159, in run
    self.plot()
  File "/Users/dlombard/py_env/lib/python2.7/site-packages/mtools/mplotqueries/mplotqueries.py", line 611, in plot
    (xlim_min, xlim_max)))
  File "/Users/dlombard/py_env/lib/python2.7/site-packages/mtools/mplotqueries/plottypes/base_type.py", line 114, in plot
    group_artists = self.plot_group(group, idx + ith_plot, axis)
  File "/Users/dlombard/py_env/lib/python2.7/site-packages/mtools/mplotqueries/plottypes/scatter_type.py", line 67, in plot_group
    if self.regex_mode:
AttributeError: 'ScatterPlotType' object has no attribute 'regex_mode'
`
### Expected behavior
Expected the plots to be shown
Seems like the code fails (for me) at `if self.regex_mode`

###Suggestion: 
replace `if` by try and except in `mtools/mplotqueries/plottypes/scatter_type.py`

### Steps to reproduce the actual/current behavior
Run mplotqueries. The same issue happened for me with previous versions (1.4.x, 1.3.x)

### Environment

| Software         | Version
| ---------------- | -------
| mtools           | 1.5.1
| Operating system | Mac OS High Sierra

**Comment by stennie** [comment]
@dlombard What is the full `mplotqueries` command line that you are running?

Your output includes [loading an overlay](http://blog.rueckstiess.com/mtools/mplotqueries.html#overlays), so if you aren't doing this intentionally perhaps there are some outdated overlays from previous plotting to remove. Can you check `mplotqueries --overlay list` to see if this might be the case?

Thanks,
Stennie

**Comment by dlombard** [comment]
You are 100% right Stennie.

I tried several mplotqueries commands such as:
`mplotqueries --logscale mongodb.log.2018-07-22T05-31-30`
`mplotqueries mongodb.log --type histogram` etc.

All failed with the error above. 

As you indicated, I ran `mplotqueries --overlay list` and found an existing overlay:
`
(py_env) Davensons-MacBook-Pro-2:mongodb dlombard$ mplotqueries --overlay list
Existing overlays:
   613ae3dc
`

I then ran `mplotqueries --overlay reset` and it fixed the issue.

Maybe we could add a log entry to indicate that an overlay is being loaded?

Thanks!
