### ISSUE TITLE
Error parsing log file

### ISSUE THREAD

**Issue by CraigKennedy** [rueckstiess/mtools#728]
Several utilities (mloginfo, mlogvis, mplotqueries) having issues with this [mongo.log](https://github.com/rueckstiess/mtools/files/3428324/mongo.log).

Call Stack:
```
  File "/usr/local/lib/python3.7/site-packages/mtools/util/logfile.py", line 260, in __iter__
    raise e
  File "/usr/local/lib/python3.7/site-packages/mtools/util/logfile.py", line 248, in __iter__
    le = self.next()
  File "/usr/local/lib/python3.7/site-packages/mtools/util/logfile.py", line 217, in next
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/bin/mloginfo", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/mtools/mloginfo/mloginfo.py", line 95, in main
    tool.run()
  File "/usr/local/lib/python3.7/site-packages/mtools/mloginfo/mloginfo.py", line 90, in run
    section.run()
  File "/usr/local/lib/python3.7/site-packages/mtools/mloginfo/sections/query_section.py", line 65, in run
    for i, le in enumerate(logfile):
RuntimeError: generator raised StopIteration
```
 
### Environment

| Software         | Version
| ---------------- | -------
| mtools           | 1.5.3 |
| MongoDB server   | 4.0.10 |
| Operating system | osx 10.14.6 |
| Python | 3.7.4 |

**Comment by stennie** [comment]
@CraigKennedy mtools 1.5.3 is only tested with [Python 2.7 and 3.6](http://blog.rueckstiess.com/mtools/install.html#prerequisites).

Support for Python 3.7 will be included in the 1.6.0 release later this month (which also drops support for Python 2.7).

The error you are encountering is a consequence of a backward-breaking change in Python 3.7: https://www.python.org/dev/peps/pep-0479/.

Regards,
Stennie
