### ISSUE TITLE
need help how to use mlaunch command

### ISSUE THREAD

**Issue by luciferhs** [rueckstiess/mtools#737]
[root@master bin]# mlaunch init --single
Failed to launch mongod
Traceback (most recent call last):
  File "/usr/local/bin/mlaunch", line 11, in <module>
    load_entry_point('mtools==1.5.3', 'console_scripts', 'mlaunch')()
  File "/usr/local/python3/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py", line 2068, in main
    tool.run()
  File "/usr/local/python3/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py", line 542, in run
    getattr(self, self.args['command'])()
  File "/usr/local/python3/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py", line 575, in init
    current_version = self.getMongoDVersion()
  File "/usr/local/python3/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py", line 821, in getMongoDVersion
    raise e
  File "/usr/local/python3/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py", line 818, in getMongoDVersion
    stdout=subprocess.PIPE, shell=False)
  File "/usr/local/python3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/python3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mongod': 'mongod'

please help me！！！

**Comment by rueckstiess** [comment]
Hi, it looks like `mlaunch` couldn't find the `mongod` binary. Do you have MongoDB installed and is it accessible in your PATH environment variable? You can confirm with `which mongod`. It should return a path, e.g. like this: `/usr/local/bin/mongod`
