### ISSUE TITLE
`mlaunch list` throws typeError for a sharded deployment

### ISSUE THREAD

**Issue by itay-ct** [rueckstiess/mtools#770]
mlaunch init & mlaunch stop works fine. However 'mlaunch list' returns
Traceback (most recent call last):
  File "/usr/local/bin/mlaunch", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py", line 2074, in main
    tool.run()
  File "/usr/local/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py", line 548, in run
    getattr(self, self.args['command'])()
  File "/usr/local/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py", line 1058, in list
    print_table(print_docs)
  File "/usr/local/lib/python3.7/site-packages/mtools/util/print_table.py", line 16, in print_table
    for row in rows if hasattr(row, '__iter__')) for k in keys]
  File "/usr/local/lib/python3.7/site-packages/mtools/util/print_table.py", line 16, in <listcomp>
    for row in rows if hasattr(row, '__iter__')) for k in keys]
  File "/usr/local/lib/python3.7/site-packages/mtools/util/print_table.py", line 16, in <genexpr>
    for row in rows if hasattr(row, '__iter__')) for k in keys]
TypeError: string indices must be integers

| Software         | Version
| ---------------- | -------
| mtools           |  mtools version 1.6.1 || Python 3.7.6 (default, Dec 30 2019, 19:38:26) [Clang
11.0.0 (clang-1100.0.33.16)]
| MongoDB server   |  4.2.2
| Operating system | macos 10.15.2

**Comment by stennie** [comment]
@itay-ct I can't reproduce this problem in Python 3.7.4 with a trivial `mlaunch init --single; mlaunch stop; mlaunch list`.

Can you comment with the exact command lines you are using and the output of `mlaunch --version`?

Thanks,
Stennie

**Comment by itay-ct** [comment]
Hi Stennie,
mlaunch --version returns:
```
mtools version 1.6.1 || Python 3.7.6 (default, Dec 30 2019, 19:38:26) [Clang
11.0.0 (clang-1100.0.33.16)]
```
I've deleted the data folder and after an init this seems to work fine now. I'll report back in case this happens again.

**Comment by stennie** [comment]
@itay-ct Thanks for the version and steps to reproduce (I can repro the same issue).
