### ISSUE TITLE
mloginfo "SyntaxError: invalid syntax"

### ISSUE THREAD

**Issue by Simone-cogno** [rueckstiess/mtools#771]
I try to use mloginfo but it fails to lunch because of a sytax error.
 
### Expected behavior

mloginfo should work, and not having syntax errors.

### Actual/current behavior

` mloginfo /usr/local/var/mongodb/info.log --queries
Traceback (most recent call last):
  File "/usr/local/bin/mloginfo", line 9, in <module>
    load_entry_point('mtools==1.6.1', 'console_scripts', 'mloginfo')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/mtools/mloginfo/mloginfo.py", line 75
    timezone = f"UTC {tzdt.strftime('%z')}"
                                          ^
SyntaxError: invalid syntax`

### Environment

I have installed in the machine python2 and  python.

| Software         | Version
| ---------------- | -------
| mtools           | 1.6.1
| MongoDB server   | 4.2
| Operating system | Mac OS X

**Comment by stennie** [comment]
@Simone-cogno mtools 1.6.0+ [requires Python 3.6 or newer](https://github.com/rueckstiess/mtools#requirements-and-installation-instructions).

The last version of mtools to support Python 2.7 was 1.5.3.  You can either upgrade to Python 3 or install the older version with `pip install mtools==1.5.3`.

Note: [Python 2 is no longer supported](https://pythonclock.org/).
