### ISSUE TITLE
TypeError running mloginfo --distinct --verbose

### ISSUE THREAD

**Issue by niccottrell** [rueckstiess/mtools#781]
### Actual/current behavior

`mloginfo --distinct server_mongosD.log` is fine but reports:
```
distinct couldn't match 2217 lines
to show non-matched lines, run with --verbose.
```

`mloginfo --distinct server_mongosD.log --verbose` gives:
```
Traceback (most recent call last):
  File "/Users/nic/anaconda3/bin/mloginfo", line 10, in <module>
    sys.exit(main())
  File "/Users/nic/anaconda3/lib/python3.7/site-packages/mtools/mloginfo/mloginfo.py", line 108, in main
    tool.run()
  File "/Users/nic/anaconda3/lib/python3.7/site-packages/mtools/mloginfo/mloginfo.py", line 103, in run
    section.run()
  File "/Users/nic/anaconda3/lib/python3.7/site-packages/mtools/mloginfo/sections/distinct_section.py", line 92, in run
    print("couldn't match:" + logevent)
TypeError: can only concatenate str (not "LogEvent") to str
```

### Environment

| Software         | Version
| ---------------- | -------
| mtools           | 1.6.1
| MongoDB server   |  mongos 3.6.12
| Operating system | Mac / Python 3.7.3 (default, Mar 27 2019, 16:54:48) [Clang

**Comment by stennie** [comment]
A fix has already been committed for mtools 1.6.2 (see #769)

Regards,
Stennie
