### ISSUE TITLE
mlaunch list throws exception on macOS 10.14

### ISSUE THREAD

**Issue by rychipman** [rueckstiess/mtools#799]
This looks very similar to #387, but with a newer version of macOS and a newer version of psutil. I attempted to downgrade psutil to 5.6.3 (the min required version), but that didn't seem to solve the issue either.

### Expected behavior
As part of an automated testing script, we run `mlaunch init` and then `mlaunch list`. We expect both to succeed, but `mlaunch list` occasionally fails with the stack trace provided below.

### Actual/current behavior
```
Traceback (most recent call last):
  File "/data/mci/807f89a00c509e1089167ddac43414f5/src/github.com/10gen/sqlproxy/testdata/artifacts/mlaunch/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 352, in catch_zombie
    yield
  File "/data/mci/807f89a00c509e1089167ddac43414f5/src/github.com/10gen/sqlproxy/testdata/artifacts/mlaunch/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 418, in cmdline
    return cext.proc_cmdline(self.pid)
ProcessLookupError: [Errno 3] No such process (originated from sysctl)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/data/mci/807f89a00c509e1089167ddac43414f5/src/github.com/10gen/sqlproxy/testdata/artifacts/mlaunch/venv/bin/mlaunch", line 8, in <module>
    sys.exit(main())
  File "/data/mci/807f89a00c509e1089167ddac43414f5/src/github.com/10gen/sqlproxy/testdata/artifacts/mlaunch/venv/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py", line 2068, in main
    tool.run()
  File "/data/mci/807f89a00c509e1089167ddac43414f5/src/github.com/10gen/sqlproxy/testdata/artifacts/mlaunch/venv/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py", line 542, in run
    getattr(self, self.args['command'])()
  File "/data/mci/807f89a00c509e1089167ddac43414f5/src/github.com/10gen/sqlproxy/testdata/artifacts/mlaunch/venv/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py", line 1026, in list
    processes = self._get_processes()
  File "/data/mci/807f89a00c509e1089167ddac43414f5/src/github.com/10gen/sqlproxy/testdata/artifacts/mlaunch/venv/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py", line 1746, in _get_processes
    p_port = p.cmdline()[p.cmdline().index('--port') + 1]
  File "/data/mci/807f89a00c509e1089167ddac43414f5/src/github.com/10gen/sqlproxy/testdata/artifacts/mlaunch/venv/lib/python3.7/site-packages/psutil/__init__.py", line 690, in cmdline
    return self._proc.cmdline()
  File "/data/mci/807f89a00c509e1089167ddac43414f5/src/github.com/10gen/sqlproxy/testdata/artifacts/mlaunch/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 334, in wrapper
    return fun(self, *args, **kwargs)
  File "/data/mci/807f89a00c509e1089167ddac43414f5/src/github.com/10gen/sqlproxy/testdata/artifacts/mlaunch/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 418, in cmdline
    return cext.proc_cmdline(self.pid)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/data/mci/807f89a00c509e1089167ddac43414f5/src/github.com/10gen/sqlproxy/testdata/artifacts/mlaunch/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 363, in catch_zombie
    raise ZombieProcess(proc.pid, proc._name, proc._ppid)
psutil.ZombieProcess: psutil.ZombieProcess process still exists but it's a zombie (pid=1653, name='mongod')
```

### Steps to reproduce the actual/current behavior
Run `mlaunch init`, followed by `mlaunch list`. The issue does not reproduce consistently, but shows up in 30 to 50 percent of the tasks.

### Environment

| Software         | Version
| ---------------- | -------
| mtools           | 1.6.3
| Python           | 3.7.5
| MongoDB server   | 4.3-latest
| Operating system | macOS 10.14

**Comment by stennie** [comment]
I haven't been able to repro this issue and 10.14 (Mojave) is now EOL from Apple as of Oct 2021.

I bumped psutil to the latest (5.8.0) in the `develop` branch for mtools 1.7.0.

If this is still reproducible for you on newer macOS, please reopen with updated details.

Thanks,
Stennie
