### ISSUE TITLE
_wait_for_primary tries to connect to entire replicaset

### ISSUE THREAD

**Issue by PDAHubbard** [rueckstiess/mtools#852]
Steps to reproduce:

1. Run mlaunch init with the --replicaset and --auth parameters:
```
mlaunch init --replicaset --name rs0 --port 30000 --dir db --auth
```
2. Observe failure:
```
pymongo.errors.ConfigurationError: Cannot specify multiple hosts with directConnection=true
```
Full trace (mtools version 1.7.1-dev || Python 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]):
```
$ mlaunch init --replicaset --name rs0 --port 30000 --dir db --auth
Generating keyfile: /home/peterh/tradecraft/data/db/keyfile
launching: "mongod" on port 30000
launching: "mongod" on port 30001
launching: "mongod" on port 30002
replica set 'rs0' initialized.
waiting for primary to add a user.
Traceback (most recent call last):
  File "/home/peterh/.local/bin/mlaunch", line 11, in <module>
    load_entry_point('mtools', 'console_scripts', 'mlaunch')()
  File "/home/peterh/dev/mtools/mtools/mlaunch/mlaunch.py", line 2222, in main
    tool.run()
  File "/home/peterh/dev/mtools/mtools/mlaunch/mlaunch.py", line 620, in run
    getattr(self, self.args['command'])()
  File "/home/peterh/dev/mtools/mtools/mlaunch/mlaunch.py", line 826, in init
    if self._wait_for_primary():
  File "/home/peterh/dev/mtools/mtools/mlaunch/mlaunch.py", line 1917, in _wait_for_primary
    mrsc = self.client(hosts, replicaSet=rs_name,
  File "/home/peterh/dev/mtools/mtools/mlaunch/mlaunch.py", line 936, in client
    return MongoConnection(host_and_port, **kwargs)
  File "/home/peterh/dev/mtools/mtools/mlaunch/mlaunch.py", line 60, in __init__
    Connection.__init__(self, *args, **kwargs)
  File "/home/peterh/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 706, in __init__
    _check_options(seeds, opts)
  File "/home/peterh/.local/lib/python3.8/site-packages/pymongo/uri_parser.py", line 381, in _check_options
    raise ConfigurationError(
pymongo.errors.ConfigurationError: Cannot specify multiple hosts with directConnection=true
```

**Comment by stennie** [comment]
Fixed in `develop` branch for next mtools release
