### ISSUE TITLE
mlaunch uses ssl_cert_reqs which does not exist in pymongo 4.0

### ISSUE THREAD

**Issue by p-mongo** [rueckstiess/mtools#857]
Trying to launch a standalone with auth using pymongo 4:

### Expected behavior

Deployment launches

### Actual/current behavior

```
+ python3 -m mtools.mlaunch.mlaunch --dir /tmpfs/db --binarypath /opt/mongodb/bin --setParameter enableTestCommands=1 --setParameter diagnosticDataCollectionEnabled=false --single --auth --username bob --password pwd123 --sslMode requireSSL --sslPEMKeyFile spec/support/certificates/server-second-level-bundle.pem --sslCAFile spec/support/certificates/ca.crt --sslClientCertificate spec/support/certificates/client.pem
/opt/python37/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py:362: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if (LooseVersion(self.current_version) >= LooseVersion("4.2.0")):
/opt/python37/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py:669: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if (LooseVersion(self.current_version) >= LooseVersion("3.3.0") or
Traceback (most recent call last):
  File "/opt/python37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/python37/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py", line 2226, in <module>
    sys.exit(main())
  File "/opt/python37/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py", line 2222, in main
    tool.run()
  File "/opt/python37/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py", line 620, in run
    getattr(self, self.args['command'])()
  File "/opt/python37/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py", line 674, in init
    self._construct_cmdlines()
  File "/opt/python37/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py", line 1969, in _construct_cmdlines
    self.discover()
  File "/opt/python37/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py", line 1281, in discover
    running = self.is_running(port)
  File "/opt/python37/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py", line 1385, in is_running
    con = self.client('localhost:%s' % port)
  File "/opt/python37/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py", line 936, in client
    return MongoConnection(host_and_port, **kwargs)
  File "/opt/python37/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py", line 60, in __init__
    Connection.__init__(self, *args, **kwargs)
  File "/opt/python37/lib/python3.7/site-packages/pymongo/mongo_client.py", line 739, in __init__
    dict(common.validate(keyword_opts.cased_key(k), v) for k, v in keyword_opts.items())
  File "/opt/python37/lib/python3.7/site-packages/pymongo/mongo_client.py", line 739, in <genexpr>
    dict(common.validate(keyword_opts.cased_key(k), v) for k, v in keyword_opts.items())
  File "/opt/python37/lib/python3.7/site-packages/pymongo/common.py", line 754, in validate
    value = validator(option, value)
  File "/opt/python37/lib/python3.7/site-packages/pymongo/common.py", line 159, in raise_config_error
    raise ConfigurationError("Unknown option %s" % (key,))
pymongo.errors.ConfigurationError: Unknown option ssl_cert_reqs
/home/w/apps/ruby-driver/spec/shared/lib/mrss/docker_runner.rb:168:in `run_command': Process exited with code 1 (RuntimeError)
	from /home/w/apps/ruby-driver/spec/shared/lib/mrss/docker_runner.rb:117:in `run_tests'
	from /home/w/apps/ruby-driver/spec/shared/lib/mrss/docker_runner.rb:33:in `run'
	from ./.evergreen/test-on-docker:11:in `<main>'
```

### Steps to reproduce the actual/current behavior

See command in the above output.

### Environment

| Software         | Version
| ---------------- | -------
| mtools           | 1.7.0
| Python           | 3.7
| MongoDB server   | n/a
| Operating system | Linux debian testing

The ssl_cert_reqs appears to not exist in pymongo 4.0, yet mlaunch is referencing it:

```
serene2% git g ssl.cert.reqs
mtools/mlaunch/mlaunch.py:                    opts['ssl_cert_reqs'] = ssl.CERT_NONE
mtools/mlaunch/mlaunch.py:                        opts['ssl_cert_reqs'] = ssl.CERT_OPTIONAL
```

**Comment by stennie** [comment]
Fixed via #885 (thanks @autarch!)
