### ISSUE TITLE
dateutil dependency

### ISSUE THREAD

**Issue by p-mongo** [rueckstiess/mtools#864]
mlaunch appears to depend on dateutil, but this dependency is not in setup.py.

### Expected behavior

mlaunch works

### Actual/current behavior

```
[2022-05-17 17:14:19.246] + python3 -m mtools.mlaunch.mlaunch --dir /data/mci/15cf8537d30af678f2c494b8a123eba1/src/../drivers-tools/.evergreen/orchestration/db --binarypath /data/mci/15cf8537d30af678f2c494b8a123eba1/src/../drivers-tools/.evergreen/orchestration/mdb/mongodb-linux-x86_64-enterprise-ubuntu2004-6.0.0-rc5/bin --setParameter enableTestCommands=1 --setParameter acceptApiVersion2=1 --setParameter diagnosticDataCollectionEnabled=false --single
[2022-05-17 17:14:19.314] Traceback (most recent call last):
[2022-05-17 17:14:19.314]   File "/opt/python/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
[2022-05-17 17:14:19.314]     "__main__", mod_spec)
[2022-05-17 17:14:19.314]   File "/opt/python/3.7/lib/python3.7/runpy.py", line 85, in _run_code
[2022-05-17 17:14:19.314]     exec(code, run_globals)
[2022-05-17 17:14:19.314]   File "/data/mci/15cf8537d30af678f2c494b8a123eba1/drivers-tools/.evergreen/orchestration/venv/lib/python3.7/site-packages/mtools/mlaunch/mlaunch.py", line 21, in <module>
[2022-05-17 17:14:19.314]     from mtools.util.cmdlinetool import BaseCmdLineTool
[2022-05-17 17:14:19.314]   File "/data/mci/15cf8537d30af678f2c494b8a123eba1/drivers-tools/.evergreen/orchestration/venv/lib/python3.7/site-packages/mtools/util/cmdlinetool.py", line 12, in <module>
[2022-05-17 17:14:19.314]     from dateutil.tz import tzutc
[2022-05-17 17:14:19.314] ModuleNotFoundError: No module named 'dateutil'
[2022/05/17 17:14:19.321] Command failed: shell script encountered problem: exit code 1
```

### Steps to reproduce the actual/current behavior

Invocation copied above

### Environment

| Software         | Version
| ---------------- | -------
| mtools           | 1.7.0
| Python           | 3.7.12
| MongoDB server   |
| Operating system | Debian

**Comment by stennie** [comment]
Thanks @p-mongo. `python-dateutil` is in `requirements.txt` but is missing from `setup.py`.
