### ISSUE TITLE
mtools version number is not compatible with PEP 440

### ISSUE THREAD

**Issue by normansu-tw** [rueckstiess/mtools#882]
I got this message during install mtools. 

    .../setuptools/dist.py:530: UserWarning: Normalizing '1.7.1-dev' to '1.7.1.dev0'

### Actual/current behavior

when execute  mlaunch,  I got this error message.

    Traceback (most recent call last):</br>
      File "/usr/bin/mlaunch", line 33, in <module></br>
        sys.exit(load_entry_point('mtools==1.7.1.dev0', 'console_scripts', 'mlaunch')())</br>
      File "/usr/bin/mlaunch", line 22, in importlib_load_entry_point</br>
        for entry_point in distribution(dist_name).entry_points</br>
      File "/usr/lib/python3.9/importlib/metadata.py", line 542, in distribution</br>
        return Distribution.from_name(distribution_name)</br>
      File "/usr/lib/python3.9/importlib/metadata.py", line 196, in from_name</br>
        raise PackageNotFoundError(name)</br>
    importlib.metadata.PackageNotFoundError: mtools

And I try to verify the version of mtools

    /.../~/mtools# python3
    Python 3.9.13 (main, May 23 2022, 22:02:02) </br>
    [GCC 7.5.0] on linux</br>
    Type "help", "copyright", "credits" or "license" for more information.</br>
       >>>>import mtools</br>
       >>>>print(mtools.__version__)</br>
     1.7.1-dev

| Software         | Version
| ---------------- | -------
| mtools           | 1.7.1-dev0
| Python           | 3.9.13
| Operating system | Ubuntu 18.04

**Comment by normansu-tw** [comment]
[PEP 440](https://peps.python.org/pep-0440/)

**Comment by stennie** [comment]
Hi @normansu-tw,

The -dev versions should only be used on the `develop` branch, which is work in progress and not published to PyPi.

However, it looks like the convention for PEP 440 should be addressed if `-dev0` is used instead of `-dev`. Can you confirm?

Regards,
Stennie

**Comment by stennie** [comment]
From PEP 440:
> Development releases allow omitting the numeral in which case it is implicitly assumed to be 0. The normal form for this is to include the 0 explicitly. This allows versions such as 1.2.dev which is normalized to 1.2.dev0.

It looks like this happened in your original install from the `develop` branch:
> Normalizing '1.7.1-dev' to '1.7.1.dev0'

... but installing led to a mismatch in the generated `mlaunch` script:
>   File "/usr/bin/mlaunch", line 33, in <module></br>
    sys.exit(load_entry_point('mtools==1.7.1.dev0', 'console_scripts', 'mlaunch')())</br>
